name: Create EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

      region:
        description: "AWS Region"
        required: true
        default: "us-east-1"

      instance_type:
        description: "EC2 Instance Type"
        required: true
        default: "t2.micro"

      instance_name:
        description: "EC2 Instance Name"
        required: true
        default: "gitops-ec2"

permissions:
  contents: read

jobs:
  create-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Create EC2
        run: |
          aws ec2 run-instances \
            --image-id ami-08188a5a4dfdbd573 \
            --instance-type ${{ inputs.instance_type }} \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${{ inputs.instance_name }}},{Key=Environment,Value=${{ inputs.environment }}}]"
```
